# Generated by Django 3.2 on 2021-04-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simonsays', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='highscore',
            field=models.IntegerField(default=0),
        ),
    ]
